module.exports = {
  rules: {
    'for-direction': 'off',
    'getter-return': 'error',
    'no-async-promise-executor': 'error',
    'no-var': 'error',
    'block-scoped-var': 'error',
    'class-methods-use-this': 'off',
    'eqeqeq': ['error', 'always'],
    'func-names': ['error', 'always'],
    'new-cap': ['error', {
      'newIsCap': true,
      'capIsNew': false,
    }],
    'no-bitwise': 'off',
    'no-plusplus': 'off',
    'no-console': 'off',
    'no-void': ['error', {
      'allowAsStatement': true,
    }],
    'no-useless-return': 'error',
    'no-return-assign': ['error', 'always'],
    'no-return-await': 'error',
    'no-throw-literal': 'error',
    'no-useless-catch': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-escape': 'error',
    'no-useless-rename': ['error', {
      'ignoreDestructuring': false,
      'ignoreImport': false,
      'ignoreExport': false,
    }],
    'no-useless-backreference': 'error',
    'no-useless-call': 'error',
    'no-useless-concat': 'error',
    'no-useless-constructor': 'error',
    'prefer-arrow-callback': 'error',
    'arrow-parens': ['error', 'always'],
    'prefer-const': ['error', {
      'destructuring': 'any',
      'ignoreReadBeforeAssign': false,
    }],
    'require-await': 'error',
    'yoda': 'error',
    'block-spacing': ['error', 'always'],
    'brace-style': 'error',
    'comma-dangle': ['error', 'always-multiline'],
    'comma-spacing': ['error', {
      'before': false,
      'after': true,
    }],
    'computed-property-spacing': 'off',
    'quotes': ['error', 'single'],
    'indent': ['error', 2, {
      'SwitchCase': 1,
    }],
    'no-lonely-if': 'error',
    'no-shadow': 'error',
    'no-shadow-restricted-names': 'error',
    'no-unused-vars': 'error',
    'no-use-before-define': 'error',
    'semi': ['error', 'always'],
    'max-len': ['error', 100, 2, {
      'ignoreUrls': true,
      'ignoreComments': true,
      'ignoreRegExpLiterals': true,
      'ignoreStrings': true,
      'ignoreTemplateLiterals': true,
    }],
    'eol-last': ['error', 'always'],
    'import/newline-after-import': 'error',
    'space-before-function-paren': ['error', 'always'],
  },
};
