name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linting:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn
      - name: Lint
        run: yarn lint
